src/main/java/pl/margor/hello/FileUploadBean.java
package pl.margor.hello;

import lombok.Getter;
import lombok.Setter;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import java.io.Serializable;

@Component("fileUploadBean")
@Scope("request")
public class FileUploadBean implements Serializable {

    @Getter
    @Setter
    private UploadedFile file;

    public String handleFileUpload(FileUploadEvent fileUploadEvent) {
        this.file = fileUploadEvent.getFile();
        if (file != null) {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage("File uploaded successfully"));
        } else {
            FacesContext.getCurrentInstance().addMessage(null, new FacesMessage(FacesMessage.SEVERITY_WARN, "Warning file was not uploaded", "Size of file is null. Is this ok? "));
        }

        return null;
    }
}

src/main/java/pl/margor/hello/TestBean.java
package pl.margor.hello;

import lombok.Getter;
import lombok.RequiredArgsConstructor;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.io.Serializable;
import javax.annotation.PostConstruct;
import pl.margor.service.HelloService;
import pl.margor.springutils.Redirector;

@Component("testBean")
@Scope("view")
@RequiredArgsConstructor
public class TestBean implements Serializable {

    private final HelloService helloSrv;
    private final Redirector redirector;
    @Getter private int counter;

    @PostConstruct
    private void init() {
        counter = 1;
    }

    /*
     * actions
     */
    public void inc() {
        counter++;
    }

    public void nextPage() throws IOException {
        redirector.redirect("nextpage.jsf");
    }

    public void prevPage() throws IOException {
        redirector.redirect("index.jsf");
    }

    public String getSrvMsg() {
        return helloSrv.getHelloMsg();
    }

}

src/main/webapp/login.xhtml
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html">
<h:head>
    <title>Spring 4 Security  + JSF 2 + PrimeFaces 5  Integration Example</title>
</h:head>
<h:body>
    <h3>Spring 4 Security  + JSF 2 + PrimeFaces 5  Integration Example</h3>
    <font color="red">
        <h:outputLabel value="${SPRING_SECURITY_LAST_EXCEPTION.message}"/>
    </font>
    <form action="${request.contextPath}/appLogin" method="POST">
        <h:outputLabel value="Enter UserName:" />
        <input type="text" name="app_username"/><br/><br/>
        <h:outputLabel value="Enter Password:" />
        <input type="password" name="app_password"/> <br/><br/>
        <input type="submit" value="Login"/>
        <input type="hidden" name="${_csrf.parameterName}" value="${_csrf.token}"/>
    </form>
</h:body>
</html>

src/main/webapp/secured/index.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
<h:head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    </h:head>
    <h:body>
        <h:form id="helloFormId">
            <h:panelGrid columns="1">
                <f:facet name="header">
                    Kontrolki index
                </f:facet>
                <h:outputText value="Hello world" />
                <h:outputText value="#{testBean.counter}" />
                <p:commandButton value="Inc" 
                                 action="#{testBean.inc()}"
                                 update="helloFormId" />
                <p:commandButton value="Next page"
                                 action="#{testBean.nextPage()}"/>
                <h:outputText value="Service msg:" />
                <h:outputText value="#{testBean.srvMsg}" />
            </h:panelGrid>
        </h:form>
    </h:body>
</html>

src/main/webapp/secured/nextpage.xhtml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui">
<h:head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    </h:head>
    <h:body>
        <h:form id="helloFormId">
            <h:panelGrid columns="1">
                <f:facet name="header">
                    Kontrolki next page
                </f:facet>
                <h:outputText value="Hello world" />
                <h:outputText value="#{testBean.counter}" />
                <p:commandButton value="Inc" 
                                 action="#{testBean.inc()}"
                                 update="helloFormId" />
                <p:commandButton value="Next page"
                                 action="#{testBean.nextPage()}"/>
                <p:commandButton value="Prev page"
                                 action="#{testBean.prevPage()}"/>
            </h:panelGrid>
        </h:form>
    </h:body>
</html>